### ISSUE TITLE
Decide and design UI screens

### ISSUE THREAD

**Issue by kokrui** [ong-fan-club/NUSRoaming#3]
## Description

We should plan out what screens our frontend will contain, and come up with basic designs for them in Figma.
 
## Notes

N/A

## Tasks

- [ ] Decide necessary screens 
- [ ] Briefly describe / label the purpose of each screen
- [ ] Design the screens in Figma

## References

- N/A
